### ISSUE TITLE
请问核心怎么手动导入呢，更新一直失败

### ISSUE THREAD

**Issue by 13582351091** [YukidouSatoru/sphia#2]
### Bug report checklist

- [ ] If you have the ability and time, you can try to fix this bug
- [X] I have searched the [issues](https://github.com/YukidouSatoru/sphia/issues)
- [X] Ensure there is only one bug report in this issue
- [X] Ensure the bug has not been fixed in the [latest build](https://github.com/YukidouSatoru/sphia/actions/workflows/build.yml)

### System

macOS Intel

### System version

macOS

### Description

请问核心怎么手动导入呢，更新一直失败

### Reproduction

请问核心怎么手动导入呢，更新一直失败

**Comment by 13582351091** [comment]
![Uploading 41707711629_.pic.jpg…]()

**Comment by YukidouSatoru** [comment]
尝试[最新构建](https://github.com/YukidouSatoru/sphia/actions/runs/7892297938)，运行前备份数据
